In [16]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [17]:
tf.__version__

'2.13.0'

# dataset

In [18]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [19]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [20]:
y

array([1, 0, 1, ..., 1, 1, 0])

# Encoding

 - gender - Label Encoder

In [21]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()
X[:,2] = Le.fit_transform(X[:,2])

In [22]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

- geography - One Hot Encoding

In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

- dummy variable moves in front column

In [26]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

# split

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# scale

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# ANN

In [30]:
ann = tf.keras.models.Sequential()

- input layer and first hidden layer

In [31]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

- second hidden layer

In [32]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

- output layer

In [34]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## training

In [35]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [37]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3313 - accuracy: 0.8676
Epoch 2/200
250/250 [==============================] - 0s 972us/step - loss: 0.3309 - accuracy: 0.8669
Epoch 3/200
250/250 [==============================] - 0s 673us/step - loss: 0.3311 - accuracy: 0.8661
Epoch 4/200
250/250 [==============================] - 0s 549us/step - loss: 0.3309 - accuracy: 0.8674
Epoch 5/200
250/250 [==============================] - 0s 508us/step - loss: 0.3310 - accuracy: 0.8666
Epoch 6/200
250/250 [==============================] - 0s 536us/step - loss: 0.3308 - accuracy: 0.8676
Epoch 7/200
250/250 [==============================] - 0s 511us/step - loss: 0.3307 - accuracy: 0.8656
Epoch 8/200
250/250 [==============================] - 0s 532us/step - loss: 0.3303 - accuracy: 0.8674
Epoch 9/200
250/250 [==============================] - 0s 512us/step - loss: 0.3303 - accuracy: 0.8669
Epoch 10/200
250/250 [==============================] - 0s 559us/step - los

# Train

In [40]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 546us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1515   80]
 [ 189  216]]


0.8655